### ISSUE TITLE
Hacktoberfest: SendGrid Current Status

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-php#79] opened 2017-10-31 16:04 UTC
## SendGrid DX team current status:
- Wow
- OMG
- THANK YOU

Hacktoberfest 2017 has completely blown us away. We have had over 900 pull requests from over 300 contributors all in the last 30 days. That is more PRs than we normally get in 2 years! 
We are actively working to review, comment, and/or merge as many PRs as we possibly can as quickly as we can.

We are currently working on “intaking” all the PRs that have come in, oldest first (we have about 400 remaining to go through). We are making sure that each PR we review is one we have a chance of merging - there have been a couple spammy items that came through. Due to the massive influx of requests so far, @thinkingserious and @mbernier have been working nights and weekends all month just to keep up! We’re not even mad, this is amazing!  
## Hey, that’s great for you - but what about my shirt!
If you have signed the CLA before 11/1, but haven’t had a PR merged yet, do not despair! We know we are behind on even just commenting on every PR to show you that we received it (something we typically do). If you submitted a mergeable (non-spam, actually adds value to the project) PR during October 2017, we will grant access to [this page](https://dx.sendgrid.com/swag) to redeem your shirt, sticker, and hacker pin. Next year, we will be sure to communicate this information sooner. We are sorry for any confusion we have caused. We appreciate those of you who have reached out to find out what’s going on! 

## What can I do to help move things along?
**Have you signed the CLA yet?** 
We can only merge items from contributors who signed the CLA

**Can you help another contributor?** 
If you can identify potential problems, add suggestions, or even leave a comment with your review of another PR (Looks good to me! Or I approve this change), that would help us review those PRs much faster, making it easier to get to your PR.

**Do you even write tests, friend?** 
If you see a place where we could have a test to validate a piece of functionality, add it in. We know We know! It’s just another PR we have to review and merge. You’re right, it is! However, the more tests we have, the earlier our CI tool can catch issues, saving us a review as well as back and forth time. 

@bertuss, @ladhadha, @mptap, @pushkyn, @ssiddhantsharma, @thepriefy, @uppe-r, @yudhik11

**Comment by ssiddhantsharma** [comment] 2017-11-01 16:43
How Can I help an another contributer.
I am ready to help with it.

**Comment by thinkingserious** [comment] 2017-11-01 18:35
Hi @ssiddhantsharma!

Thanks for offering to help :)

Assuming PHP is your language of choice, please start with any open PRs here:
- https://github.com/sendgrid/smtpapi-php/pulls
- https://github.com/sendgrid/php-http-client/pulls
- https://github.com/sendgrid/sendgrid-php/pulls

Any feedback you have, even it's just LGTM is helpful in speeding our ability to close those PRs.

Then, if you still have time, here are the remaining open issues:
- https://github.com/sendgrid/smtpapi-php/issues
- https://github.com/sendgrid/php-http-client/issues
- https://github.com/sendgrid/sendgrid-php/issues

If there are issues you can easily solve, PRs are greatly appreciated; otherwise, any feedback that can help towards resolving the issue is very helpful as well.

With Best Regards,

Elmer

**Comment by mbernier** [comment] 2017-11-02 15:21
@ssiddhantsharma you rock!! Thank you!

**Comment by ssiddhantsharma** [comment] 2017-11-02 16:57
Working on the PR's related to PHP as I am front end developer.

Will make some time on working on the related issues in the coming week.
Feels great to contribute to OS and your firm.
Thanks

**Comment by ladhadha** [comment] 2017-11-03 06:59
Sorry maybe this is out of topic. @thinkingserious, just trying to contribute more for some sendgrid OS projects but I got trouble while trying to get my own SENDGRID_API_KEY, I've regitered to sendgrid, but my account was declined.

**Comment by thinkingserious** [comment] 2017-11-03 17:44
Hi @ladhadha,

Could you please ail is at dx@sendgrid.com with your SendGrid username?

Thanks!

Elmer

**Closed** 2018-02-28 20:37 UTC
